# Generated by Django 5.2.6 on 2025-09-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(max_length=50)),
                ('joined_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
