# Generated by Django 5.2.6 on 2025-09-10 04:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blogs_author_alter_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
